name: Lint & Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint & Format
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm format
      - run: pnpm lint
  test:
    runs-on: ubuntu-latest
    name: Test Crawler API
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install pnpm
        run: corepack enable
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
      - name: Upload coverage reports to Codecov
        if: ${{ github.ref_name == 'main' }}
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{secrets.CODECOV_TOKEN}}
