name: Lint & Format Ci

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint & Format
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm format
      - run: pnpm lint
