name: Package Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest
    name: Version Check
    steps:
      - uses: actions/checkout@v2.4.2
      # 检查npm包的版本号和本地packages.json的版本号是否重复
      # https://github.com/marketplace/actions/version-check
      - uses: EndBug/version-check@v2.1.0
        with:
          file-url: https://unpkg.com/@wtto00/spider-crawler@latest/package.json
          static-checking: localIsNew
